---
- name: Tomcat deployment playbook
  hosts: tomcat_nodes
  become: yes
  vars:
    tomcat_ver: 10.1.39
    ui_manager_username: manager
    ui_manager_pass: manager
    ui_admin_username: admin
    ui_admin_pass: admin
    deployer_username: deployer
    deployer_pass: deployer
  roles:
    - tomcat
